site_name: applybn
repo_name: Anaxagor/applybn/
repo_url: https://github.com/Anaxagor/applybn/
theme:
  name: material
  locale: en
  markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.instant.prefetch
    - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Getting Started:
    - index.md
    - getting-started/installation.md
  - User Guide:
    - index.md
    - Concept Explainer: user-guide/explainable_module/concept_explainer.md
    - Interventional Explainer: user-guide/explainable_module/interventional_analysis.md
    - CNN Filter Analysis: user-guide/explainable_module/cnn_filter_analysis.md
    - NMI-based Feature selection: user-guide/feature_selection/nmi_feature_selection.md
    - Causal-based Feature selection: user-guide/feature_selection/causal_feature_selection.md
    # Add concepts and theoretical background?
  
  - API Reference:
      - Core:
          - logger: api/core/logger.md
          - estimators: api/core/estimators.md
          - estimators_factory: api/core/estimators_factory.md
          # - exceptions: api/core/exceptions.md
          # - progress_bar: api/core/progress_bar.md
      - Causal explanation methods:
          - Concepts Explanations: api/explainable/concepts_causal.md
          - Interventional Explanations: api/explainable/interventions_causal.md
          - CNN Filter Importance: api/explainable/cnn_filter_importance.md
      - Feature selection methods:
          - NMI-based Feature selection: api/feature_selection/nmi_feature_selection.md
          - Causal-based Feature selection: api/feature_selection/causal_feature_selection.md
      - Feature extraction:
          - BN-based feature extraction: api/feature_extraction.md
      - Outlier detection:
          - api/outlier_detection/outlier_detection.md
          - Tabular outlier detection: api/outlier_detection/tabular_outliers.md
          - Time series outlier detection: api/outlier_detection/ts_outliers.md
  - Examples:
      - Tabular Data: examples/tabular_data.md
      - Time Series Data: examples/time_series_data.md
      - Feature Selection with NMIFeatureSelector: examples/nmi_feature_selection.md
      - Robustness Analysis for Causal Feature Selection: examples/causal_feature_selection.md
      - Custom Estimators: examples/custom_estimators.md

  - Development and Contribution:
      - development/contributing.md

#extra:
#  social:
#    - icon: fontawesome/brands/github
#      link: https://github.com/myusername/myproject
plugins:
  - search
  - mkdocstrings
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: True
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
        generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js