name: black-action
on: [push, pull_request]
jobs:
  linter_name:
    name: Run black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rickstaa/action-black@v1.3.3
        with:
          black_args: "."